php:
  risky: true
  version: 8
  preset: laravel
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name: ".php"
    not-name:
      - ".blade.php"