php:
  risky: true
  version: 7
  preset: laravel
  enabled:
    - ternary_to_elvis_operator
  disabled:
    - single_import_per_statement
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name: ".php"
    not-name:
      - ".blade.php"
      - "_ide_helper.php"
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
